# Generated by Django 4.1.7 on 2023-04-04 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('sur_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('sur_sur_name', models.CharField(db_index=True, max_length=20, verbose_name='Отчество')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('descriptions', models.TextField(max_length=300, verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('vk_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='VK')),
                ('hh_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='HH')),
                ('behance_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='BH')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('following', models.ManyToManyField(related_name='followers', to='Accounts.user', verbose_name='Подписки')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.specs', verbose_name='Спецализация')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('sum_registred', models.IntegerField(default=0, verbose_name='Сумма оценок зареганных')),
                ('count_registred', models.IntegerField(default=0, verbose_name='Колисчество оценок зареганных')),
                ('sum_unregistred', models.IntegerField(default=0, verbose_name='Сумма оценок незареганных')),
                ('count_unregistred', models.IntegerField(default=0, verbose_name='Количество оценок незареганных')),
                ('descriptions', models.TextField(max_length=300, verbose_name='Описание')),
                ('github_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='github')),
                ('behance_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='BH')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.user', verbose_name='Автор проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.project', verbose_name='Фото проекта')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower1', to='Accounts.user', verbose_name='Кто подписался')),
                ('follow_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following1', to='Accounts.user', verbose_name='На кого подписался')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['id'],
            },
        ),
    ]
