# Generated by Django 4.1.7 on 2023-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_user_following_alter_follow_follow_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='behance_url',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='BH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hh_url',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='HH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_url',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='VK'),
        ),
    ]
