# Generated by Django 4.1.7 on 2023-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='media/accounts/<django.db.models.fields.SlugField>', verbose_name='Фото'),
        ),
    ]
