# Generated by Django 4.1.7 on 2023-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='behance_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='BH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hh_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='HH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='VK'),
        ),
    ]
