# Generated by Django 4.1.7 on 2023-04-04 16:17

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_user_behance_url_alter_user_hh_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=Accounts.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
