# Generated by Django 4.1.7 on 2023-04-04 16:27

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=Accounts.models.image_directory_path),
        ),
    ]
